# Generated by Django 4.2.5 on 2023-09-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place1', models.CharField(max_length=255)),
                ('place2', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
            ],
        ),
    ]
